/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhoexploratorio.telas;

/**
 *
 * @author karla
 */
public class frame_3 extends javax.swing.JFrame {

    /**
     * Creates new form frame_3
     */
    public frame_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titulo2 = new javax.swing.JLabel();
        Stanozolol = new javax.swing.JCheckBox();
        Primobolan = new javax.swing.JCheckBox();
        Dianabol = new javax.swing.JCheckBox();
        Hemogenin = new javax.swing.JCheckBox();
        Oxandrolona = new javax.swing.JCheckBox();
        Durateston = new javax.swing.JCheckBox();
        botao_mostrar = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        botao_esvaziar = new javax.swing.JButton();
        titulo1 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo2.setText("Adicione ítens ao Carrinho: ");

        Stanozolol.setText("Stanozolol");
        Stanozolol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StanozololActionPerformed(evt);
            }
        });

        Primobolan.setText("Primobolan");

        Dianabol.setText("Dianabol");

        Hemogenin.setText("Hemogenin");

        Oxandrolona.setText("Oxandrolona");

        Durateston.setText("Durateston");

        botao_mostrar.setText("Mostrar Carrinho");
        botao_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_mostrarActionPerformed(evt);
            }
        });

        resultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        botao_esvaziar.setText("Esvaziar Carrinho");
        botao_esvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_esvaziarActionPerformed(evt);
            }
        });

        titulo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulo1.setText("Loja Maromba");

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dianabol)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Durateston)
                                    .addComponent(Primobolan)
                                    .addComponent(Stanozolol)
                                    .addComponent(Hemogenin)
                                    .addComponent(titulo2)
                                    .addComponent(Oxandrolona))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(titulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botao_mostrar)
                        .addGap(39, 39, 39)
                        .addComponent(botao_esvaziar)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Voltar)
                        .addGap(270, 270, 270))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titulo2)
                .addGap(8, 8, 8)
                .addComponent(Stanozolol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Primobolan)
                .addGap(8, 8, 8)
                .addComponent(Dianabol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hemogenin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Oxandrolona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Durateston)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_mostrar)
                    .addComponent(botao_esvaziar))
                .addGap(29, 29, 29)
                .addComponent(Voltar)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StanozololActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StanozololActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StanozololActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void botao_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_mostrarActionPerformed
        String mensagem = "";
        if (Stanozolol.isSelected()){
            mensagem+= "Stanozolol\n\n";
        } 
        if (Primobolan.isSelected()){
           mensagem+= "Primobolan\n\n"; 
        }
        if (Dianabol.isSelected()){
           mensagem+= "Dianabol\n\n"; 
        }
        if (Hemogenin.isSelected()){
           mensagem+= "Hemogenin\n\n"; 
        }
        if (Oxandrolona.isSelected()){
           mensagem+= "Oxandrolona\n\n"; 
        }
        if (Durateston.isSelected()){
           mensagem+= "Durateston\n\n"; 
        }
        resultado.setText(mensagem);
            // TODO add your handling code here:
    }//GEN-LAST:event_botao_mostrarActionPerformed

    private void botao_esvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_esvaziarActionPerformed
       resultado.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_botao_esvaziarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        new MenuInicial().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Dianabol;
    private javax.swing.JCheckBox Durateston;
    private javax.swing.JCheckBox Hemogenin;
    private javax.swing.JCheckBox Oxandrolona;
    private javax.swing.JCheckBox Primobolan;
    private javax.swing.JCheckBox Stanozolol;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton botao_esvaziar;
    private javax.swing.JButton botao_mostrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField resultado;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
