
package trabalhoexploratorio.telas;

/**  TRABALHO EXPLORATORIO DE PROGRAMÇÃO ORIENTADA A OBJETOS - 2022/10
 *
 * @author José Samuel Pereira                 - Ra: 22016916-2 - Pura Fome
 * @author Karla Duarte Ferreira               - Ra: 21144154-2
 * @author Eduardo Richard da Silva Nascimento - Ra: 21161812-2 - richwrd
 */

public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo_menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollTable = new javax.swing.JButton();
        chekbox = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        colorchoise = new javax.swing.JButton();
        telaspinner = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        botaoProgreesBar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fundo_menu.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("=-=-=-=-=-=-=-=-MENU INICIAL=-=-=-=-=-=-=-=-");

        scrollTable.setText("<<Table e Scroll Bar>>");
        scrollTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrollTableActionPerformed(evt);
            }
        });

        chekbox.setText("<<CheckBox>>");
        chekbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekboxActionPerformed(evt);
            }
        });

        jButton4.setText("<<Slider>>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        colorchoise.setText("TESTE DE CORES COLOR CHOOSER");
        colorchoise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorchoiseActionPerformed(evt);
            }
        });

        telaspinner.setText("CALCULADORA SPINNER");
        telaspinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaspinnerActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 153, 255));
        jButton8.setText("CREDITOS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        botaoProgreesBar.setText("<<Progess Bar>>");
        botaoProgreesBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProgreesBarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundo_menuLayout = new javax.swing.GroupLayout(fundo_menu);
        fundo_menu.setLayout(fundo_menuLayout);
        fundo_menuLayout.setHorizontalGroup(
            fundo_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundo_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundo_menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(scrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chekbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorchoise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telaspinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoProgreesBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fundo_menuLayout.setVerticalGroup(
            fundo_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundo_menuLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(botaoProgreesBar)
                .addGap(30, 30, 30)
                .addComponent(scrollTable)
                .addGap(30, 30, 30)
                .addComponent(chekbox)
                .addGap(30, 30, 30)
                .addComponent(jButton4)
                .addGap(30, 30, 30)
                .addComponent(colorchoise)
                .addGap(30, 30, 30)
                .addComponent(telaspinner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fundo_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoProgreesBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProgreesBarActionPerformed
        // abrir tela Progress Bar e fechar a tela atual
        new ProgressBar().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botaoProgreesBarActionPerformed

    private void scrollTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrollTableActionPerformed
        // botão para abrir a tela ScrollBarTable e fechar a tela atual

        new Table().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_scrollTableActionPerformed

    private void chekboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekboxActionPerformed
//botão para entrar no Checkbox
        new frame_3().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_chekboxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //botão para entrar no Slider1
        new Slider1().setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // botão para abrir a tela de creditos e fechar a tela atual
        new Creditos().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoProgreesBar;
    private javax.swing.JButton chekbox;
    private javax.swing.JButton colorchoise;
    private javax.swing.JPanel fundo_menu;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton scrollTable;
    private javax.swing.JButton telaspinner;
    // End of variables declaration//GEN-END:variables
}
